Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -45,11 +45,11 @@ jobs:
           echo "${{ secrets.AWS_EC2_KEY }}" > miclave.pem
           chmod 600 miclave.pem
 
-      # Paso 2: Actualizar e instalar Docker en la instancia EC2 (Instancia 1)
+            # Paso 2: Actualizar e instalar Docker en la instancia EC2 (Instancia 1)
       - name: Update system and install Docker (Instance 1)
         run: |
-          ssh -o StrictHostmiclaveChecking=no -i miclave.pem ec2-user@${{ secrets.AWS_EC2_HOST_QA1 }} "sudo yum update -y"
-          ssh -o StrictHostmiclaveChecking=no -i miclave.pem ec2-user@${{ secrets.AWS_EC2_HOST_QA1 }} "if ! command -v docker &> /dev/null; then echo 'Docker not found, installing...'; sudo yum install -y docker; sudo systemctl start docker; sudo systemctl enable docker; else echo 'Docker is already installed.'; fi"
+          ssh -o StrictHostKeyChecking=no -i miclave.pem ec2-user@${{ secrets.AWS_EC2_HOST_QA1 }} "sudo yum update -y"
+          ssh -o StrictHostKeyChecking=no -i miclave.pem ec2-user@${{ secrets.AWS_EC2_HOST_QA1 }} "if ! command -v docker &> /dev/null; then echo 'Docker not found, installing...'; sudo yum install -y docker; sudo systemctl start docker; sudo systemctl enable docker; else echo 'Docker is already installed.'; fi"
       
       # Paso 3: Desplegar el contenedor Docker en la instancia EC2 (Instancia 1)
       - name: Deploy Docker Container (Instance 1)
@@ -57,4 +57,4 @@ jobs:
           ssh -o StrictHostKeyChecking=no -i miclave.pem ec2-user@${{ secrets.AWS_EC2_HOST_QA1 }} "sudo docker stop calculator-microservices || true"
           ssh -o StrictHostKeyChecking=no -i miclave.pem ec2-user@${{ secrets.AWS_EC2_HOST_QA1 }} "sudo docker rm calculator-microservices || true"
           ssh -o StrictHostKeyChecking=no -i miclave.pem ec2-user@${{ secrets.AWS_EC2_HOST_QA1 }} "sudo docker pull ${{ secrets.DOCKER_USERNAME }}/calculator-microservices:latest"
-          ssh -o StrictHostKeyChecking=no -i miclave.pem ec2-user@${{ secrets.AWS_EC2_HOST_QA1 }} "sudo docker run -d -p 3000:3000 --name calculator-microservices -e DB_HOST=${{ secrets.DB_HOST }} -e DB_USER=${{ secrets.DB_USER }} -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} -e DB_NAME=${{ secrets.DB_NAME }} ${{ secrets.DOCKER_USERNAME }}/calculator-microservices:latest"
+          ssh -o StrictHostKeyChecking=no -i miclave.pem ec2-user@${{ secrets.AWS_EC2_HOST_QA1 }} "sudo docker run -d -p 3010:3010 --name calculator-microservices -e DB_HOST=${{ secrets.DB_HOST }} -e DB_USER=${{ secrets.DB_USER }} -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} -e DB_NAME=${{ secrets.DB_NAME }} ${{ secrets.DOCKER_USERNAME }}/calculator-microservices:latest"
